feat: task19, rack middleware
DenisTDA/middleware pull request #1
Opened 2022-07-05 07:55 UTC by DenisTDA

2022-07-05 15:48 UTC, VidgarVii requested changes

2022-07-05 15:48 UTC, VidgarVii commented on time_app.rb
> +  PATH = '/time'.freeze
Для настройки ContentType по умолчанию можно воспользоваться настройкой через Rack::ContentType

https://www.rubydoc.info/gems/rack/Rack/ContentType

и этот код будет не нужным

2022-07-05 15:48 UTC, VidgarVii commented on time_app.rb
> +  GOOD_REQUEST = 200
для статусов есть готовое решение
https://www.rubydoc.info/gems/rack/Rack/Utils#HTTP_STATUS_CODES-constant

2022-07-05 15:48 UTC, VidgarVii commented on time_body.rb
> +class TimeBody
вот этот класс не стоит реализовывать как промежуточное ПО (middleware)
функции промежуточного ПО - посредник, переходник, фильтр
здесь же мы скорее имеем обработку пришедших данных, их валидацию
было бы более верно реализовать этот функционал, как обычный класс
далее в Апп создать объект этого класса, проверить валиден ли этот объект и в зависимости от этого либо вернут ответ (отформатированное время по ТЗ), либо вернуть статус 404
но выбор что вернуть и сам возврат нужно реализовывать в Апп
как-то так:
```ruby
result = ParamParser.new(params)
if result.valid?
  ....
else
  ...
end
```
похоже на экшены контроллеров в рельсах
а класс `ParamsParser` должен отработать примерно, как модель в рельсах
принял параметры, обработал, по запросу ответил валидный или нет результат обработки

2022-07-05 15:48 UTC, VidgarVii commented on time_body.rb
> +  GOOD_REQUEST = 200
опять прослеживается размазывание логики( Еще хуже то, что уже есть такие же константы
Простой принцип абстрагирования. Если тебе надо что-то сделать - создай такой объект, который будет ЭТО делать. Не надо всех объектов учить делать одно и то же.

2022-07-05 15:48 UTC, VidgarVii commented on time_app.rb
> +    [status, { 'Content-Type' => 'text/plain' }, body]
для формирования ответа можно использовать [Rack::Response](https://www.rubydoc.info/github/rack/rack/Rack/Response)

2022-07-06 15:00 UTC, DenisTDA commented on time_app.rb
> +    [status, { 'Content-Type' => 'text/plain' }, body]
Не очень понял зачем использовать Rack::Response, если и массивам все замечательно возвращает? Для более сложных вариантов?

2022-07-06 15:13 UTC, VidgarVii commented on time_app.rb
> +    [status, { 'Content-Type' => 'text/plain' }, body]
можно и массивом, если это будет выглядеть минималистично. Но это согласно ООП, мы всегда должны делегировать выполнения процессов другим объектам

2022-07-06 15:19 UTC, VidgarVii requested changes

2022-07-06 15:19 UTC, VidgarVii commented on params_parser.rb
> +    end
Тут нарушение инверсии зависимостей. И так же не ушли от божественного класса.
Класс не должен знать ни про какие статусы, он должен только бизнес-логику содержать. Задача - сделать так, чтоб класс можно было использовать в других сценариях, например для консольного интерфейса (там нет никаких статусов ответа).

2022-07-06 15:19 UTC, VidgarVii commented on params_parser.rb
> +
лишний отступ

2022-07-06 15:19 UTC, VidgarVii commented on time_app.rb
> +      status, body = Rack::Utils::SYMBOL_TO_STATUS_CODE[:not_found], ["Invalid path\n"]
проверку path можно делегировать на утилиту Rack::URLMap. Он как раз будет возвращать 404, если путь не верен

```ruby
require_relative 'time_app'
ROUTES = {
  '/time' => TimeApp.new
}


run Rack::URLMap.new(ROUTES)
```

2022-07-06 15:19 UTC, VidgarVii commented on time_app.rb
> +      status, body = Rack::Utils::SYMBOL_TO_STATUS_CODE[:not_found], ["Invalid path\n"]
если передан не верный формат, то 404 не подходящий статус

2022-07-06 19:55 UTC, DenisTDA commented on time_app.rb
> +      status, body = Rack::Utils::SYMBOL_TO_STATUS_CODE[:not_found], ["Invalid path\n"]
я этого не понимаю

2022-07-07 06:15 UTC, VidgarVii requested changes

2022-07-07 06:15 UTC, VidgarVii commented on time_app.rb
> +    end
вложенные условия всегда читаются плохо и с ними сложно работать. Можно переписать использую guard clause

2022-07-07 06:15 UTC, VidgarVii commented on time_app.rb
> +  end
как я уже писал. функциональность 404 можно делегировать утилите Rack
Request это на много больше чем просто путь URL. Не корректное называние метода

2022-07-07 06:15 UTC, VidgarVii commented on time_app.rb
> +        body = result.body_bad_params
если есть body то где-то есть и head? Похоже на старые отсылки к запросу http внутри доменой области
Можно было использовать общепринятые методы #errors (уже по всю использовали в рельсе) или #failures

2022-07-07 06:15 UTC, VidgarVii commented on params_parser.rb
> +    ["Unknown time format: #{str}\n"]
почему тут возвращается массив? Как я уже писал ранее. Внутренних компонентов ПО не должно волновать то как и где их используют. Представление — это внешняя среда. Забота класса TimeApp и Rack

2022-07-07 06:15 UTC, VidgarVii commented on params_parser.rb
> +class ParamsParser
класс не только парсит параметры, но и показывает время. Мне кажется для времени он и создавался. А проверка параметров это всего-лишь предусловие.
По названию можно понять, что класс просто занимается кодированием каких-то параметров

2022-07-07 10:00 UTC, DenisTDA commented on time_app.rb
> +  end
Я не понимаю, как работает эта утилита. Поэтому оставил то, что я понимаю как работает. Разбираюсь пока с утилитой.

2022-07-07 18:15 UTC, merged